# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-15 05:59
from __future__ import unicode_literals

import RobApp1.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SheetName', models.CharField(default='TestDefault', max_length=255)),
                ('StartLine', models.FloatField(default=11)),
                ('EmptyLineNum', models.FloatField(default=11)),
                ('filepath', models.FileField(upload_to=RobApp1.models.upload_to_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RobApp1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
