# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-21 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_auto_20170721_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_cdap',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
