# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-21 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_model_cdap_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_cdap',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
