# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-21 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_auto_20170721_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_cdap',
            name='type',
            field=models.CharField(choices=[('python', 'Python'), ('r', 'R'), ('knime', 'Knime'), ('spotfire', 'Spotfire'), ('excel', 'Excel')], max_length=32),
        ),
    ]
