# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-24 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_auto_20170721_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_cdap',
            name='modelcmd',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='model_cdap',
            name='modelpath',
            field=models.FileField(null=True, upload_to='coreapp/rawscripts'),
        ),
    ]
