# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-26 09:38
from __future__ import unicode_literals

import coreapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_auto_20170724_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_cdap',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='model_cdap',
            name='modelpath',
            field=models.FileField(null=True, upload_to=coreapp.models.upload_to_path),
        ),
    ]
