# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-27 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0011_auto_20170726_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_cdap',
            old_name='user',
            new_name='author',
        ),
    ]
