# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-02 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0012_auto_20170727_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_cdap',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date published'),
        ),
    ]
