# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-28 07:59
from __future__ import unicode_literals

import coreapp2.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_cdap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(choices=[('python', 'Python'), ('r', 'R'), ('knime', 'Knime'), ('spotfire', 'Spotfire'), ('excel', 'Excel')], max_length=32)),
                ('modelpath', models.FileField(null=True, upload_to=coreapp2.models.upload_to_path)),
                ('modelcmd', models.TextField(null=True)),
                ('slug', models.SlugField(unique=True)),
                ('owner', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(null=True, verbose_name='date published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
